### ISSUE TITLE
Execution error using singularity exec

### ISSUE THREAD

**Issue by UpalabdhaD** [metagenlab/mummer2circos#11]
**System Configuration:**
OS: Debian GNU/Linux bookworm/sid x86_64 
Host: HP Z6 G4 Workstation 
Kernel: 5.18.0-2-amd64 
Uptime: 1 day, 6 hours, 21 mins 
Packages: 2306 (dpkg) 
CPU: Intel Xeon Silver 4214R (24) @ 3.500GHz 
GPU: NVIDIA Quadro T400 Mobile 
Memory: 5000MiB / 64108MiB 

**Command:**
> singularity exec mummer2circos.simg mummer2circos -r GMI1000.fasta -q SEPPX05_genomic.fna  -gb SEPPX05_genomic.gbk -l
fasta1 GMI1000.fasta

[input_files_mummer2circos.zip](https://github.com/metagenlab/mummer2circos/files/9220479/input_files_mummer2circos.zip)

**Output:**
nucmer -b 200 -c 65 -g 90 -l 20 -p SEPPX05_genomic GMI1000.fasta SEPPX05_genomic.fna
show-coords -T -r -c -L 100 -I 30 SEPPX05_genomic.delta > SEPPX05_genomic.coords
show_ticks         = yes
 show_tick_labels   = yes
 
 <ticks>
 tick_label_font    = condensed
 radius             = dims(ideogram,radius_outer)
 label_offset       = 8p
 label_size         = 4p
 color              = black
 thickness          = 2p
 
 
 <tick>
 show_ticks         = yes
 skip_first_label = no
 multiplier   = 10/1u
 spacing           = 1u
 size              = 5p
 show_label        = no
 label_size        = 5p
 format            = %%.1d
 </tick>
  <tick>
 show_ticks         = yes
 skip_first_label = no
 multiplier   = 10/1u
 spacing           = 10u
 size              = 15p
 show_label        = yes
 label_size        = 25p
 format            = %%.1d kb
 thickness         = 2p
 </tick>

 
 
 </ticks>

Traceback (most recent call last):
  File "/opt/conda/envs/mummer2circos/bin/mummer2circos", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/__init__.py", line 67, in main
    blast_identity_cutoff=args.blast_identity_cutoff)
  File "/opt/conda/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/mummer2circos.py", line 94, in __init__
    minus, plus = self.gbk2circos_data(gbk2orf)
  File "/opt/conda/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/mummer2circos.py", line 1145, in gbk2circos_data
    start = str(feature.location.start + self.contigs_add[record.id][0])
KeyError: 'NZ_CP088237.1'

**Comment by tpillone** [comment]
Hi @UpalabdhaD 

The genbank file should match the reference genome (-r) and not the query genome (-q), you have to reverse the query and the reference in your command: 

```  
singularity exec mummer2circos.simg mummer2circos **-q** GMI1000.fasta **-r** SEPPX05_genomic.fna -gb SEPPX05_genomic.gbk -l
```

**Comment by UpalabdhaD** [comment]
Your answer resolved the issue.
thanks
