### ISSUE TITLE
Conda installation fails

### ISSUE THREAD

**Issue by guillemmasfiol** [metagenlab/mummer2circos#6]
Hi,

thank you for this interesting tool!  I've been trying to install the software via the conda environment file in different Unix-based systems without success. The installation just keeps at "Solving environment" eternally, without ever concluding.

Are there any particularities of the python environment file to consider for installation? How can I overcome the issue?

thank you in advance!

**Comment by guillemmasfiol** [comment]
It seems the issue comes due to incompatibilities between packages: 

`Found conflicts! Looking for incompatible packages.                                                                                                                                                  failed                                                                                                                                                                                                 |
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                                                                                                               failed                                                                                                                                                                                                 -

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package openssl conflicts for:
pip -> python[version='>=3.6'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=3.0.0,<4.0a0|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']
biopython=1.72 -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a|>=3.0.0,<4.0a0|>=1.1.1i,<1.1.2a']
matplotlib -> python[version='>=3.9,<3.10.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=3.0.0,<4.0a0|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']
blast -> curl[version='>=7.77.0,<8.0a0'] -> openssl[version='>=1.1.1l,<1.1.2a|>=3.0.0,<4.0a0']

Package libgcc conflicts for:
libwebp=0.5 -> giflib -> libgcc
matplotlib -> pyqt -> libgcc
blast -> libgcc
circos -> perl-gd -> libgcc

Package libzlib conflicts for:
circos -> perl-gd -> libzlib[version='>=1.2.11,<1.3.0a0']
matplotlib -> python[version='>=3.9,<3.10.0a0'] -> libzlib[version='1.2.11|1.2.11|>=1.2.11,<1.3.0a0',build='h36c2ea0_1012|h36c2ea0_1013']
pip -> python[version='>=3.6'] -> libzlib[version='>=1.2.11,<1.3.0a0']
blast -> curl[version='>=7.77.0,<8.0a0'] -> libzlib[version='1.2.11|1.2.11|>=1.2.11,<1.3.0a0',build='h36c2ea0_1012|h36c2ea0_1013']
biopython=1.72 -> python[version='>=3.6,<3.7.0a0'] -> libzlib[version='>=1.2.11,<1.3.0a0']
libwebp=0.5 -> libtiff -> libzlib[version='>=1.2.11,<1.3.0a0']

Package libstdcxx-ng conflicts for:
pip -> python[version='>=3.6'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
libwebp=0.5 -> libtiff -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
blast -> pcre[version='>=8.41,<9.0a0'] -> libstdcxx-ng[version='>=7.2.0|>=9.4.0']
circos -> perl-gd -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=9.4.0']
biopython=1.72 -> numpy -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=9.4.0|>=9.3.0|>=7.5.0']
matplotlib -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
matplotlib -> matplotlib-base[version='>=3.5.1,<3.5.2.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.5.0|>=9.4.0|>=9.3.0']
mummer -> libstdcxx-ng[version='>=7.3.0|>=9.3.0|>=9.4.0']
blast -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0']
biopython=1.72 -> libstdcxx-ng[version='>=7.2.0']

Package icu conflicts for:
matplotlib -> icu[version='>=58.2,<59.0a0']
matplotlib -> matplotlib-base[version='>=3.3.0,<3.3.1.0a0'] -> icu[version='>=64.2,<65.0a0|>=67.1,<68.0a0']
blast -> boost=1.61 -> icu=56

Package python_abi conflicts for:
matplotlib -> python_abi[version='3.10.*|3.9.*|3.7|3.7.*|3.8.*|3.6|3.6.*',build='*_cp39|*_cp310|*_pypy37_pp73|*_cp37m|*_cp38|*_pypy36_pp73|*_cp36m']
matplotlib -> matplotlib-base[version='>=2.2.5,<2.2.6.0a0'] -> python_abi=2.7[build=*_cp27mu]

Package zlib conflicts for:
matplotlib -> zlib[version='>=1.2.11,<1.3.0a0']
matplotlib -> python[version='>=3.6,<3.7.0a0'] -> zlib[version='1.2.*|1.2.11|1.2.8|1.2.11.*']

Package pip conflicts for:
biopython=1.72 -> python[version='>=3.6,<3.7.0a0'] -> pip
matplotlib -> python[version='>=3.9,<3.10.0a0'] -> pip
pip

Package _libgcc_mutex conflicts for:
mummer -> libgcc-ng[version='>=9.4.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge|main']
matplotlib -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1|0.1',build='main|main|conda_forge']
blast -> libgcc-ng[version='>=9.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge|main']
biopython=1.72 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1|0.1',build='main|main|conda_forge']

Package mkl conflicts for:
biopython=1.72 -> numpy -> mkl[version='>=2018.0.0,<2019.0a0|>=2018.0.1,<2019.0a0|>=2018.0.2,<2019.0a0|>=2018.0.3,<2019.0a0|>=2019.1,<2021.0a0|>=2019.3,<2021.0a0|>=2019.4,<2021.0a0|>=2021.2.0,<2022.0a0|>=2021.3.0,<2022.0a0|>=2021.4.0,<2022.0a0|>=2019.4,<2020.0a0']
matplotlib -> numpy=1.11 -> mkl[version='>=2018.0.0,<2019.0a0|>=2018.0.1,<2019.0a0|>=2018.0.2,<2019.0a0|>=2018.0.3,<2019.0a0|>=2019.1,<2021.0a0|>=2019.4,<2021.0a0|>=2021.4.0,<2022.0a0|>=2021.3.0,<2022.0a0|>=2021.2.0,<2022.0a0|>=2019.3,<2021.0a0|>=2019.4,<2020.0a0']

Package perl-app-cpanminus conflicts for:
blast -> perl-list-moreutils -> perl-app-cpanminus
circos -> perl-list-moreutils -> perl-app-cpanminus

Package perl-threaded conflicts for:
circos -> perl-gd -> perl-threaded[version='>=5.22.0']
circos -> perl-threaded
mummer -> perl-threaded
blast -> entrez-direct -> perl-threaded

Package numpy conflicts for:
matplotlib -> numpy[version='1.10.*|1.11.*|>=1.14.6,<2.0a0']
matplotlib -> matplotlib-base[version='>=3.5.1,<3.5.2.0a0'] -> numpy[version='>=1.11.3,<2.0a0|>=1.15.4,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17|>=1.19.5,<2.0a0|>=1.21.4,<2.0a0|>=1.18.5,<2.0a0|>=1.21.2,<2.0a0|>=1.19.2,<2.0a0|>=1.17.5,<2.0a0|>=1.19.4,<2.0a0|>=1.9.3,<2.0a0']
blast -> boost[version='>=1.68.0,<1.68.1.0a0'] -> numpy[version='1.11.*|1.12.*|1.13.*|>=1.11|>=1.8|>=1.9.3,<2.0a0|>=1.9|>=1.7|>=1.19.5,<2.0a0|>=1.18.5,<2.0a0|>=1.21.4,<2.0a0|>=1.17.5,<2.0a0|>=1.16.6,<2.0a0|>=1.16.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.14.6,<2.0a0']
biopython=1.72 -> numpy[version='>=1.11.3,<2.0a0|>=1.8']

Package pypy3.7 conflicts for:
matplotlib -> python[version='>=3.7,<3.8.0a0'] -> pypy3.7[version='7.3.*|7.3.3.*|7.3.4.*|7.3.5.*|7.3.7.*']
matplotlib -> pypy3.7[version='>=7.3.3|>=7.3.4|>=7.3.5|>=7.3.7']

Package tzdata conflicts for:
pip -> python[version='>=3.6'] -> tzdata
matplotlib -> python[version='>=3.9,<3.10.0a0'] -> tzdata

Package libgcc-ng conflicts for:
matplotlib -> libgcc-ng[version='>=7.2.0|>=7.3.0']
matplotlib -> matplotlib-base[version='>=3.5.1,<3.5.2.0a0'] -> libgcc-ng[version='>=4.9|>=7.5.0|>=9.4.0|>=9.3.0']

Package python conflicts for:
matplotlib -> python[version='2.7.*|3.4.*|3.5.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
matplotlib -> pyqt -> python[version='3.10.*|3.6.*|3.9.*|3.7.*|3.8.*|>=3.6|>=3|<3']

Package perl conflicts for:
blast -> entrez-direct -> perl[version='>=5.26.2,<5.27.0a0|>=5.32.1,<6.0a0',build=*_perl5]
blast -> perl[version='5.22.0.*|>=5.26.2,<5.26.3.0a0']

Package libpng conflicts for:
libwebp=0.5 -> libpng
matplotlib -> freetype=2.6 -> libpng[version='1.6.*|>=1.6.21,<1.7|>=1.6.32,<1.6.35']
matplotlib -> libpng[version='>=1.6.23,<1.7|>=1.6.37,<1.7.0a0|>=1.6.36,<1.7.0a0|>=1.6.35,<1.7.0a0|>=1.6.34,<1.7.0a0|>=1.6.32,<1.7.0a0']

Package xz conflicts for:
biopython=1.72 -> python[version='>=3.6,<3.7.0a0'] -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
matplotlib -> python[version='>=3.9,<3.10.0a0'] -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
libwebp=0.5 -> libtiff -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
pip -> python[version='>=3.6'] -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']

Package pypy3.6 conflicts for:
matplotlib -> pypy3.6[version='>=7.3.2|>=7.3.3']
matplotlib -> tornado -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - biopython=1.72 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - blast -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - matplotlib -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - mummer -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

Note that strict channel priority may have removed packages required for satisfiability.`

**Comment by tpillone** [comment]
Hi,

For the never ending "Solving environment" problem, I would recommend using `mamba` to solve complex environments (https://github.com/mamba-org/mamba). It's a reimplementation of the conda package manager.

I could not reproduce the conflicting installation, it might be due to your specific conda installation. Could you try to remove the constrain on the biopython version in the `env.yaml` (biopython=1.72)?  
`mummer2circos` will not work properly with the latest versions of biopython, but I can update it if it's a source of conflict.

**Comment by guillemmasfiol** [comment]
Hi, 

thanks for the recommendation of mamba! it actually appears to have successfully bypassed the issue. 

Here are the steps I followed for succesfful installation:

`									# install mamba from conda: 
									conda install mamba -n base -c conda-forge
									# add conda-forge channel:
									mamba install xtensor-r -c conda-forge
									# install mummer2circos from provided environment file:
									mamba env create -f env.yaml
									# activate:
									conda activate mummer2circos
									mummer2circos --help
					`

**Comment by Yixiangzhang1996** [comment]
hi
there is a problem.
pip it works,but  not work in installing dependencies for mummer2circos.
can not find a solution...

`
  Summary:

  Install: 133 packages

  Total download: 0  B

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/miniconda3/envs/mummer2circos/bin/python', '-m', 'pip', 'install', '-U', '-r', '/mummer2circos/condaenv.xef6uwg3.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/metagenlab/mummer2circos.git (from -r /mummer2circos/condaenv.xef6uwg3.requirements.txt (line 1))
  Cloning https://github.com/metagenlab/mummer2circos.git to /tmp/pip-req-build-wiymfu4_

Pip subprocess error:
  Running command git clone --quiet https://github.com/metagenlab/mummer2circos.git /tmp/pip-req-build-wiymfu4_
  fatal: unable to access 'https://github.com/metagenlab/mummer2circos.git/': Encountered end of file
  error: subprocess-exited-with-error

  × git clone --quiet https://github.com/metagenlab/mummer2circos.git /tmp/pip-req-build-wiymfu4_ did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet https://github.com/metagenlab/mummer2circos.git /tmp/pip-req-build-wiymfu4_ did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
                                                                                      failed

CondaEnvException: Pip failed
`

**Comment by guillemmasfiol** [comment]
> hi there is a problem. pip it works,but not work in installing dependencies for mummer2circos. can not find a solution...
> 
> ` Summary:
> 
> Install: 133 packages
> 
> Total download: 0 B
> 
> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
> Preparing transaction: done Verifying transaction: done Executing transaction: done Installing pip dependencies: | Ran pip subprocess with arguments: ['/miniconda3/envs/mummer2circos/bin/python', '-m', 'pip', 'install', '-U', '-r', '/mummer2circos/condaenv.xef6uwg3.requirements.txt'] Pip subprocess output: Collecting git+https://github.com/metagenlab/mummer2circos.git (from -r /mummer2circos/condaenv.xef6uwg3.requirements.txt (line 1)) Cloning https://github.com/metagenlab/mummer2circos.git to /tmp/pip-req-build-wiymfu4_
> 
> Pip subprocess error: Running command git clone --quiet https://github.com/metagenlab/mummer2circos.git /tmp/pip-req-build-wiymfu4_ fatal: unable to access 'https://github.com/metagenlab/mummer2circos.git/': Encountered end of file error: subprocess-exited-with-error
> 
> × git clone --quiet https://github.com/metagenlab/mummer2circos.git /tmp/pip-req-build-wiymfu4_ did not run successfully. │ exit code: 128 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × git clone --quiet https://github.com/metagenlab/mummer2circos.git /tmp/pip-req-build-wiymfu4_ did not run successfully. │ exit code: 128 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. failed
> 
> CondaEnvException: Pip failed `

**Comment by guillemmasfiol** [comment]
@Yixiangzhang1996 Hi, did you try installing with mamba?

**Comment by Yixiangzhang1996** [comment]
> @Yixiangzhang1996 Hi, did you try installing with mamba?

Yes,when I ran the step of "mamba env create -f env.yaml"
it comes wrong at the installing  dependencies as I pasted above.

**Comment by Yixiangzhang1996** [comment]
> @Yixiangzhang1996 Hi, did you try installing with mamba?
![image](https://user-images.githubusercontent.com/30544004/152469015-796294fa-8c90-4147-b8ea-a3621717104f.png)
