### ISSUE TITLE
Circos modules missing

### ISSUE THREAD

**Issue by guillemmasfiol** [metagenlab/mummer2circos#9]
Hi,

thanks a lot for this tool, it looks great! I installed it using conda and when trying to run on the example dataset, I receive error messages regarding Perl modules for Circos. There is some info regarding how to install them from Circos website, but I was wondering whether they should be installed when installing mummer2circos too? 

`b"\n*** REQUIRED MODULE(S) MISSING OR OUT-OF-DATE ***\n\nYou are missing one or more Perl modules, require newer versions, or some modules failed to load. Use CPAN to install it as described in this tutorial\n\nhttp://www.circos.ca/documentation/tutorials/configuration/perl_and_modules\n\nmissing GD\n  error Can't locate GD.pm in @INC (you may need to install the GD module) (@INC contains: /home/gmasfiol/miniconda3/envs/mummer2circos/bin/lib /home/gmasfiol/miniconda3/envs/mummer2circos/bin/../lib /home/gmasfiol/miniconda3/envs/mummer2circos/bin /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/5.32/site_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/site_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/5.32/vendor_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/vendor_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/5.32/core_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/core_perl .) at (eval 39) line 1.\nmissing GD::Polyline\n  error Can't locate GD/Polyline.pm in @INC (you may need to install the GD::Polyline module) (@INC contains: /home/gmasfiol/miniconda3/envs/mummer2circos/bin/lib /home/gmasfiol/miniconda3/envs/mummer2circos/bin/../lib /home/gmasfiol/miniconda3/envs/mummer2circos/bin /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/5.32/site_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/site_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/5.32/vendor_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/vendor_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/5.32/core_perl /home/gmasfiol/miniconda3/envs/mummer2circos/lib/perl5/core_perl .) at (eval 40) line 1.\n"b''0`

Best,

Guillem

**Comment by tpillone** [comment]
Hi @guillemmasfiol, 

Thank you for your feedback. It seems that some perl modules installed by conda are not properly installed or recognized by circos. I could solve the problem by specifying specific packages in the conda env file. 
Let me know if the new conda environment works for you. 

Best

**Comment by guillemmasfiol** [comment]
Hi, 

thank you again for your quick reply, I could re-install the environment with the new yml file and successfully run the first test this time :)  Thanks for this tool!

You can close the issue, 

Best,

Guillem
